apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: style-transfer
  name: style-transfer
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: style-transfer
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: style-transfer
    spec:
      containers:
        - image: gcr.io/project-id/image-name
          imagePullPolicy: Always
          name: style-transfer
          ports:
            - containerPort: 8338
              protocol: TCP
          resources:
            limits:
              cpu: 3
              memory: 10Gi
              nvidia.com/gpu: 1
            requests:
              cpu: 3
              memory: 10Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          env:
            - name: DATE
              value: 2018-11-28T22:26:42.318Z
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
